from gtts import gTTS
import os
from langchain_groq import ChatGroq
from langchain_community.chat_message_histories import StreamlitChatMessageHistory
from langchain_core.prompts import ChatPromptTemplate, MessagesPlaceholder
from langchain_core.runnables.history import RunnableWithMessageHistory
from langchain_mongodb.chat_message_histories import MongoDBChatMessageHistory


# UPLOAD_DIR = "../frontend/front/src/audio"
# if not os.path.exists(UPLOAD_DIR):
#     os.makedirs(UPLOAD_DIR)

def get_chat_message_history():
    """
    Retrieves the chat message history for a specific session from a MongoDB database.

    Args:
        session_id (str): The unique identifier for the chat session whose history is to be retrieved.

    Returns:
        MongoDBChatMessageHistory: An instance of MongoDBChatMessageHistory configured to access the specified session's chat history.
    """
    return MongoDBChatMessageHistory(
        session_id = "user",  # "user"# Convert session_id to string if not already
        connection_string="mongodb://localhost:27017",  # MongoDB connection string
        database_name="history",  # Name of the database containing chat histories
        collection_name="chat_histories"  # Collection within the database where chat histories are stored
    )


def get_response(text, api_key):
    """
    Generate a response from the language model with memory support.

    Args:
        text (str): The user input text to process.
        api_key (str): API key for accessing the language model.

    Returns:
        str: The response generated by the AI model.
    """
           # Retrieve the chat message history for the given session
    history = get_chat_message_history()
        
    
    # Define the prompt template for the chatbot conversation
    prompt = ChatPromptTemplate.from_messages(
        [
            ("system", "You are an advanced AI chatbot capable of understanding and responding in Urdu. Your primary goal is to assist users with accurate and helpful information, answer their questions, and address their needs effectively. Ensure your responses are clear, contextually relevant, and polite. Always seek to provide detailed and precise answers based on the user's queries. Maintain a professional and supportive tone throughout the conversation, and strive to improve the user's experience by adapting to their input and preferences."),
            MessagesPlaceholder(variable_name="history"),
            ("human", "{question}"),
        ]
    )

    # Initialize the language model with specified parameters
    chat_model = ChatGroq(
        model="llama-3.1-70b-versatile",
        api_key=api_key,  
        temperature=0,  
        max_tokens=None,  
        timeout=None,   
        max_retries=2, 
    )

    # Create a chain with the prompt and language model
    chain = prompt | chat_model

    # Create a runnable chain with message history support
    chain_with_history = RunnableWithMessageHistory(
        chain,
        lambda session_id: history,  
        input_messages_key="question",  
        history_messages_key="history",  
    )

    # Add the user's message to the history
    history.add_user_message(text)
    
    # Get the AI response from the language model using the chain with history
    response = chain_with_history.invoke({"question": text}, {"configurable": {"session_id": "any"}})
    
    # Add the AI response to the history
    history.add_ai_message(response.content)
    
    # Return the response content from the AI model
    return response.content

def response_text_to_speech(text, filename):
    """Convert response text to speech and save it as an audio file.
    
    Args:
        text (str): The text to convert into speech.
        filename (str): The path where the audio file will be saved.
    """
    UPLOAD_DIR = "audio"
    #Save audio to a directory
    # Initialize the gTTS object with the given text and language
    tts = gTTS(text=text, lang='ur')
    
    # Save the generated speech to the specified file
    tts.save(os.path.join(UPLOAD_DIR, filename))